In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("US_Baby_Names_right.csv")

In [3]:
df.head(5)

   Unnamed: 0     Id     Name  Year Gender State  Count
0       11349  11350     Emma  2004      F    AK     62
1       11350  11351  Madison  2004      F    AK     48
2       11351  11352   Hannah  2004      F    AK     46
3       11352  11353    Grace  2004      F    AK     44
4       11353  11354    Emily  2004      F    AK     41

In [4]:
df.sample(10)

        Unnamed: 0       Id      Name  Year Gender State  Count
567882     3180649  3180650  Gilberto  2010      M    NC      9
664550     3740531  3740532    Cassie  2011      F    NY     14
546488     3099492  3099493  Abbygail  2006      F    NC      7
854876     4906911  4906912    Yanira  2006      F    TX     10
837006     4744028  4744029   Rolando  2005      M    TN      7
836508     4743530  4743531     Larry  2005      M    TN     37
949101     5287387  5287388    Dexter  2006      M    VA      5
474436     2631370  2631371   Zachery  2009      M    MI     17
267061     1375557  1375558      Dane  2004      M    HI     13
155995      806040   806041      Xavi  2010      M    CO      8

### Описание признаков полей

Name - Имя ребенка

Year - Год рождения

Gender - Пол

State - Штат

Count - Количество

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1016395 entries, 0 to 1016394
Data columns (total 7 columns):
 #   Column      Non-Null Count    Dtype
---  ------      --------------    -----
 0   Unnamed: 0  1016395 non-null  int64
 1   Id          1016395 non-null  int64
 2   Name        1016395 non-null  object
 3   Year        1016395 non-null  int64
 4   Gender      1016395 non-null  object
 5   State       1016395 non-null  object
 6   Count       1016395 non-null  int64
dtypes: int64(4), object(3)
memory usage: 54.3+ MB

In [8]:
df.describe()

         Unnamed: 0            Id          Year         Count
count  1.016395e+06  1.016395e+06  1.016395e+06  1.016395e+06
mean   2.830990e+06  2.830991e+06  2.009053e+03  3.485012e+01
std    1.652476e+06  1.652476e+06  3.138293e+00  9.739735e+01
min    1.134900e+04  1.135000e+04  2.004000e+03  5.000000e+00
25%    1.317326e+06  1.317328e+06  2.006000e+03  7.000000e+00
50%    2.811920e+06  2.811921e+06  2.009000e+03  1.100000e+01
75%    4.242554e+06  4.242556e+06  2.012000e+03  2.600000e+01
max    5.647425e+06  5.647426e+06  2.014000e+03  4.167000e+03

In [9]:
np.set_printoptions(suppress=True)
pd.set_option('display.float_format', lambda x: '%0.4f' % x)

In [10]:
df.describe()

        Unnamed: 0           Id         Year        Count
count 1016395.0000 1016395.0000 1016395.0000 1016395.0000
mean  2830990.4619 2830991.4619    2009.0532      34.8501
std   1652475.6515 1652475.6515       3.1383      97.3973
min     11349.0000   11350.0000    2004.0000       5.0000
25%   1317326.5000 1317327.5000    2006.0000       7.0000
50%   2811920.0000 2811921.0000    2009.0000      11.0000
75%   4242554.5000 4242555.5000    2012.0000      26.0000
max   5647425.0000 5647426.0000    2014.0000    4167.0000

In [12]:
df.describe(include=['O'])

           Name   Gender    State
count   1016395  1016395  1016395
unique    17632        2       51
top       Riley        F       CA
freq       1112   558846    76781

### Проверка на пропущенные значения

In [35]:
df.isna().sum()

Name      0
Year      0
Gender    0
State     0
Count     0
dtype: int64

In [13]:
df["Gender"].value_counts()

Gender
F    558846
M    457549
Name: count, dtype: int64

In [17]:
df[["Gender","Count"]].groupby("Gender").sum()

           Count
Gender
F       16380293
M       19041199

### Предварительная обработка данных

In [27]:
df.drop(columns=['Unnamed: 0', 'Id'], inplace=True)

In [29]:
df

            Name  Year Gender State  Count
0           Emma  2004      F    AK     62
1        Madison  2004      F    AK     48
2         Hannah  2004      F    AK     46
3          Grace  2004      F    AK     44
4          Emily  2004      F    AK     41
...          ...   ...    ...   ...    ...
1016390     Seth  2014      M    WY      5
1016391  Spencer  2014      M    WY      5
1016392     Tyce  2014      M    WY      5
1016393   Victor  2014      M    WY      5
1016394   Waylon  2014      M    WY      5

[1016395 rows x 5 columns]

In [39]:
df[["Year","Count"]].groupby("Year").sum()

        Count
Year
2004  3293984
2005  3305315
2006  3387737
2007  3412417
2008  3340318
2009  3232116
2010  3116548
2011  3079145
2012  3073858
2013  3066443
2014  3113611

In [47]:
df[["State","Count"]].groupby("State").sum().sort_values("Count")

         Count
State
WY       36019
VT       36432
AK       63649
ND       69561
DE       73060
MT       75765
SD       79547
DC       82504
RI       83499
HI       90406
ME       99368
NH      101547
ID      167128
WV      167357
NM      198657
NE      201367
NV      279767
MS      288143
AR      292659
CT      312747
IA      318773
KS      327040
OR      381556
OK      413580
SC      435359
UT      448216
KY      460790
AL      475422
LA      493505
CO      574230
WI      576679
MD      585246
MN      595801
MA      638232
MO      672772
WA      730321
TN      735102
IN      753487
AZ      808258
VA      872376
NJ      913330
MI     1038080
NC     1078680
GA     1185168
PA     1276091
OH     1286370
IL     1486991
FL     1976379
NY     2208154
TX     3791675
CA     5084647

In [49]:
df[["Name","Count"]].groupby("Name").sum().sort_values("Count",ascending=False).head(10)

           Count
Name
Jacob     242874
Emma      214852
Michael   214405
Ethan     209277
Isabella  204798
William   197894
Joshua    191551
Sophia    191446
Daniel    191440
Emily     190318

In [53]:
df[df["Name"] == "Jacob"]

          Name  Year Gender State  Count
2407     Jacob  2004      M    AK     54
2611     Jacob  2005      M    AK     58
2827     Jacob  2006      M    AK     55
3048     Jacob  2007      M    AK     49
3271     Jacob  2008      M    AK     60
...        ...   ...    ...   ...    ...
1015550  Jacob  2010      M    WY     21
1015708  Jacob  2011      M    WY     30
1015879  Jacob  2012      M    WY     28
1016056  Jacob  2013      M    WY     20
1016262  Jacob  2014      M    WY     13

[568 rows x 5 columns]

In [55]:
df[df["Name"] == "Jacob"].count()

Name      568
Year      568
Gender    568
State     568
Count     568
dtype: int64

In [57]:
len(df[df["Name"] == "Jacob"])

568

In [59]:
df[df["Name"] == "Emma"].count()

Name      566
Year      566
Gender    566
State     566
Count     566
dtype: int64

In [61]:
len(df[df["Name"] == "Emma"])

566